name: Rust Cross-Compile

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust targets
        run: rustup target add x86_64-pc-windows-gnu

      - name: Install Windows cross-compilation tools
        run: sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Build for Linux
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Build for Windows
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Collect Binaries
        run: |
          mkdir -p binaries
          cp target/x86_64-unknown-linux-gnu/release/watermark-cli binaries/watermark-cli-linux || echo "Linux binary not found"
          cp target/x86_64-pc-windows-gnu/release/watermark-cli.exe binaries/watermark-cli-windows.exe || echo "Windows binary not found"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries-cross-compiled
          path: binaries/
